In [2]:
# Imports
import numpy as np
from sklearn.impute import SimpleImputer

# Instancia o objeto
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

# Define o array
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]

# Insere os dados no objeto
imp_mean.fit(X)

# Saída
print(imp_mean.transform(X))

[[ 7.  2.  3.]
 [ 4.  2.  6.]
 [10.  2.  9.]]


In [3]:
X

[[nan, 2, 3], [4, nan, 6], [10, nan, 9]]