In [1]:
from sklearn.datasets import load_iris
from sklearn.impute import SimpleImputer
import numpy as np

In [2]:
# Carregar conjunto de dados Iris
iris = load_iris()
X, y = iris.data, iris.target

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
# Introduzir valores ausentes em algumas amostras
index_faltantes = [0, 5, 10]
X_dados_faltantes = X.copy()
X_dados_faltantes[index_faltantes] = np.nan

In [4]:
# Imputar valores ausentes usando SimpleImputer com estratégia 'mean', 'median' ou 'most_frequent'
# Sintaxe: objeto = SimpleImputer(strategy='nome_estratégia')
imputer = SimpleImputer(strategy='mean')

In [5]:
# Aplicar o objeto imputer aos dados faltantes
# Sintaxe: nome_variável = imputer.fit_transform(X_with_missing)
X_imputed = imputer.fit_transform(X_dados_faltantes)

In [6]:
# Resultado
# Sintaxe: dados_faltantes[index] e dados_imputados[index] (devido ao tamanho do dataset)
print("Amostras originais com dados faltantes:")
print(X_dados_faltantes[index_faltantes])
print("\nAmostras imputadas:")
print(X_imputed[index_faltantes])

Amostras originais com dados faltantes:
[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]

Amostras imputadas:
[[5.85442177 3.04421769 3.80340136 1.21836735]
 [5.85442177 3.04421769 3.80340136 1.21836735]
 [5.85442177 3.04421769 3.80340136 1.21836735]]
